apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-route-pgadmin
spec:
  hostnames:
    - pgadmin.k8s.prrlvr.fr
  parentRefs:
    - name: cilium-eg
      namespace: cilium
      group: gateway.networking.k8s.io
      kind: Gateway
  rules:
    - backendRefs:
        - name: pgadmin-pgadmin4
          port: 80