---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cnpg-postgres-16-vaultwarden
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: cnpg-postgres-16
  databaseReclaimPolicy: retain