---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-admin-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-admin-creds
  data:
    - secretKey: token
      remoteRef:
        key: vaultwarden/vaultwarden-admin-creds
        property: token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden-postgres-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vaultwarden-postgres-creds
  data:
    - secretKey: username
      remoteRef:
        key: postgres/users/vaultwarden
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/users/vaultwarden
        property: password