---
kind: Kustomization
namespace: argocd

resources:
  # - argocd.yml
  - cilium.yml
  - cert-manager.yml
  - coredns.yml
  # - cnpg.yml
  # - echo.yml
  # - external-secrets.yml
  # - grafana.yml
  # - ilo-exporter.yml
  # - kube-prometheus-stack.yml
  # - nfs.yml
  # - pgadmin.yml
  # - rook-ceph-cluster.yml
  # - rook-ceph-operator.yml
  # - vault.yml
