apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-eg
  namespace: cilium
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTP
      port: 80
      name: cilium-eg-web
      allowedRoutes:
        namespaces:
          from: All
