apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-eg
  namespace: cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  gatewayClassName: cilium
  listeners:
    - protocol: HTTPS
      port: 443
      name: https-echo
      hostname: "k8s.prrlvr.fr"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: echo-k8s-tls
    - protocol: HTTPS
      port: 443
      name: https
      hostname: "*.prrlvr.fr"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: wildcard-prrlvr-tls