apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-route-echo
spec:
  parentRefs:
    - name: cilium-eg
  rules:
    - backendRefs:
        - name: echo
          port: 80
