---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: forgejo-admin-creds
  data:
    - secretKey: username
      remoteRef:
        key: forgejo/forgejo-admin-creds
        property: username
    - secretKey: password
      remoteRef:
        key: forgejo/forgejo-admin-creds
        property: password
    - secretKey: email
      remoteRef:
        key: forgejo/forgejo-admin-creds
        property: email
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-postgres-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: forgejo-postgres-creds
  data:
    - secretKey: username
      remoteRef:
        key: postgres/users/forgejo
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/users/forgejo
        property: password